Encoder:
  # [from, number, module, args]
  [[-1, 1, Conv, [32, 3, 2 ] ],    # 0
   [-1, 1, Conv, [64, 3, 2 ] ],    # 1

   [ -1, 1, Conv, [ 32, 1, 1 ] ],
   [ -2, 1, Conv, [ 32, 1, 1 ] ],
   [ -1, 1, Conv, [ 32, 3, 1 ] ],
   [ -1, 1, Conv, [ 32, 3, 1 ] ],
   [ -1, 1, Conv, [ 32, 3, 1 ] ],
   [ -1, 1, Conv, [ 32, 3, 1 ] ],
   [ [ -1, -3, -5, -6 ], 1, Concat, [ 1 ] ],
   [ -1, 1, Conv, [ 128, 1, 1 ] ],

   [-1, 1, MP_C, [128]],         # 10
   [ -1, 1, Conv, [ 64, 1, 1 ] ],
   [ -2, 1, Conv, [ 64, 1, 1 ] ],
   [ -1, 1, Conv, [ 64, 3, 1 ] ],
   [ -1, 1, Conv, [ 64, 3, 1 ] ],
   [ -1, 1, Conv, [ 64, 3, 1 ] ],
   [ -1, 1, Conv, [ 64, 3, 1 ] ],
   [ [ -1, -3, -5, -6 ], 1, Concat, [ 1 ] ],
   [ -1, 1, Conv, [ 256, 1, 1 ] ],

   [-1, 1, MP_C, [256]],         # 19
   [ -1, 1, Conv, [ 128, 1, 1 ] ],
   [ -2, 1, Conv, [ 128, 1, 1 ] ],
   [ -1, 1, Conv, [ 128, 3, 1 ] ],
   [ -1, 1, Conv, [ 128, 3, 1 ] ],
   [ -1, 1, Conv, [ 128, 3, 1 ] ],
   [ -1, 1, Conv, [ 128, 3, 1 ] ],
   [ [ -1, -3, -5, -6 ], 1, Concat, [ 1 ] ],
   [ -1, 1, Conv, [ 512, 1, 1 ] ],
   [-1, 1, Mult_ECA, [512] ],    # 28
  ]

Decoder:
  [[-1, 1, SPPCSPC_group, [256]],

   [ -1, 1, Conv, [ 128, 1, 1 ] ],
   [ -2, 1, Conv, [ 128, 1, 1 ] ],
   [ -1, 1, Conv, [ 64, 3, 1 ] ],
   [ -1, 1, Conv, [ 64, 3, 1 ] ],
   [ -1, 1, Conv, [ 64, 3, 1 ] ],
   [ -1, 1, Conv, [ 64, 3, 1 ] ],
   [ [ -1, -2, -3, -4, -5, -6 ], 1, Concat, [ 1 ] ],
   [ -1, 1, Conv, [ 128, 1, 1 ] ],  # 37

   [ -1, 1, Conv, [ 64, 1, 1] ],
   [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
   [ 18, 1, Conv, [ 64, 1, 1] ],
   [ [ -1, -2 ], 1, Concat, [ 1 ] ],

   [ -1, 1, Conv, [ 64, 1, 1 ] ],
   [ -2, 1, Conv, [ 64, 1, 1 ] ],
   [ -1, 1, Conv, [ 32, 3, 1 ] ],
   [ -1, 1, Conv, [ 32, 3, 1 ] ],
   [ -1, 1, Conv, [ 32, 3, 1 ] ],
   [ -1, 1, Conv, [ 32, 3, 1 ] ],
   [ [ -1, -2, -3, -4, -5, -6 ], 1, Concat, [ 1 ] ],
   [ -1, 1, Conv, [ 64, 1, 1 ] ],  # 49

   [49, 1, RepConv, [128, 3, 1] ],
   [37, 1, RepConv, [256, 3, 1] ],

   [[50, 51], 1, Output, [] ],
  ]
